[package]
name = "ai_observer"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true  # Pour la sérialisation
serde_json.workspace = true      # Pour stocker et charger le graphe en JSON
chrono.workspace = true
rand.workspace = true
ron.workspace = true             # Format Rusty Object Notation
bincode-next.workspace = true
