[workspace]
members = [
    "semver_planner",
    "workspace_manager",
    "version_watcher",
    "rhl/middle_level",
    "ai_evolution_lab",
    "automate_projects",
    "evolve_system",
    "ia_manager",
    "publish_unl",
    "server",
    "unilang",
    "web_unl",
]
resolver = "2"

[workspace.dependencies]
bincode-next = "3.1.1"
ron = "0.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
chrono = { version = "0.4.45", features = ["serde"] }
tokio = { version = "1.52.3", features = ["full", "signal"] }
uuid = { version = "1.23.4", features = ["v4", "v7", "serde", "std"] }
walkdir = "2.5.0"
env_logger = "0.11.11"
tower = { version = "0.5.3", features = ["util"] }
thiserror = "2.0.18"
reqwest = { version = "0.13.4", features = ["json", "multipart", "blocking"] }
log = "0.4.33"
ctrlc = { version = "3.5.2", features = ["termination"] }
tower-http = { version = "0.7.0", features = ["fs", "cors"] }
sysinfo = "0.39.6"
regex = "1.12.4"
parking_lot = "0.12.5"
rand = "0.10.2"
axum = { version = "0.8.9", features = ["ws", "multipart"] }
clap = { version = "4.6.1", features = ["derive"] }
syn = { version = "2.0.118", features = ["full", "parsing"] }
