[package]
name = "evolution_ai"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode-next.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
rayon = "1.7"
ndarray = "0.15"
crossbeam = "0.8"
parking_lot.workspace = true
libloading = "0.7"
walkdir.workspace = true
syn.workspace = true
quote = "1.0"
proc-macro2 = "1.0"
axum.workspace = true
tokio.workspace = true
tower-http.workspace = true
chrono.workspace = true
ron.workspace = true
glob = "0.3"
tempfile = "3.8"
ctrlc.workspace = true
