[package]
name = "ai_evolution_lab"
version = "0.1.0"
edition = "2024"

[dependencies]
log.workspace = true
env_logger.workspace = true
serde.workspace = true
ron.workspace = true
bincode-next.workspace = true
uuid.workspace = true
rand.workspace = true
walkdir.workspace = true
chrono.workspace = true
ctrlc.workspace = true
