[package]
name = "evolve_system"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
serde_json.workspace = true
ron.workspace = true
rand.workspace = true
bincode-next.workspace = true
tokio.workspace = true
reqwest.workspace = true
scraper = "0.13"
uuid.workspace = true
syn.workspace = true
