[package]
name = "universal_browser"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode-next.workspace = true
pixels = "0.13"
winit = { version = "0.29", features = ["rwh_05"] }
log.workspace = true
env_logger.workspace = true
unilang = { path = "../unilang" }
raw-window-handle = "0.5"
reqwest.workspace = true
once_cell = "1.18"
