[package]
name = "workspace_core"
version = "0.1.0"
edition = "2024"

[dependencies]
ron.workspace = true
serde.workspace = true
toml = "0.5"
clap.workspace = true
uuid.workspace = true
bincode-next.workspace = true
thiserror.workspace = true
parking_lot.workspace = true
lru = "0.12"
metrics = "0.21"
tokio.workspace = true
serde_json.workspace = true
reqwest.workspace = true
