[package]
name = "workspace_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode-next.workspace = true
serde.workspace = true
ron.workspace = true
serde_json.workspace = true
log.workspace = true
env_logger.workspace = true
tokio.workspace = true
axum.workspace = true
tower-http.workspace = true
hyper = { version = "0.14", features = ["server"] }
tokio-tungstenite = "0.15"
futures-util = "0.3"
tower.workspace = true
