[package]
name = "ai_assistant"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
ron.workspace = true
bincode-next.workspace = true
clap.workspace = true
chrono.workspace = true
version_watcher = { path = "../version_watcher" } # Ajout de `version_watcher`
semver_planner = { path = "../semver_planner" }   # Ajout de `semver_planner`
