[package]
name = "middle_level"
version = "0.1.0"
edition = "2024"
default-run = "middle_level"  # Définit le binaire par défaut

[[bin]]
name = "rhl-lsp"
path = "src/bin/lsp.rs"

[dependencies]
bincode-next.workspace = true
tower-lsp = "0.20"
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
ron.workspace = true
url = "2.4"
regex.workspace = true
lazy_static = "1.4"
